# Site settings
title: Disturnbance
description: >- # this means to ignore newlines until "baseurl:"
  Welcome everyone!
baseurl: "/Bg-jekyll-plYou" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: ingersollms/Bg-jekyll-plYou
# remote_theme: YoussefRaafatNasry/portfolYOU

# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed

# Author Info
author:
  name: ingersollms
  image: https://images.weserv.nl/?url=https://wx3.sinaimg.cn/mw690/c0f1cb72ly1g2w0nu17k0j20yi22oh38.jpg
  email: admin@ingersollm.top
  github: ingersollms
  # twitter: ingersollms
  # linkedin: ingersollms
  facebook: sollm.inger.5
  instagram: disturnbance
  weibo: 5961170607
  pinterest: ingersollmss

# Collections
collections:
  projects:
    output: true
    permalink: /Bg-jekyll-plYou/projects/:name

# Default values for collections
defaults:
  - scope:
      path: "/Bg-jekyll-plYou/"
      type: "projects"
    values:
      layout: "page"

# Posts default Permalink
permalink: /Bg-jekyll-plYou/articles/:title

# Exclude from processing.
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
