# Site settings
title: inger
description: >- # this means to ignore newlines until "baseurl:"
  This is my blog.Welcome!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: ingersollms/ingersollms.github.io
# remote_theme: YoussefRaafatNasry/portfolYOU

# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed

# Author Info
author:
  name: ingersollms
  image: https://i2.cdn.turner.com/cnnnext/dam/assets/140926165711-john-sutter-profile-image-large-169.jpg
  email: admin@ingersollm.top
  github: ingersollms
  twitter: ingersollms
  linkedin: ingersollms
  facebook: ingersollms

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name

# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

# Posts default Permalink
permalink: articles/:title

# Exclude from processing.
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
